services:
  mongodb:
    image: mongo:latest
    container_name: local-mongodb
    restart: always
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:alpine
    container_name: local-redis
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:
