services:
  aerospike:
    image: aerospike/aerospike-server:latest
    container_name: local-aerospike
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NAMESPACE=test
    volumes:
      - aerospike_data:/opt/aerospike/data

volumes:
  aerospike_data:
